# Generated by Django 3.0.3 on 2020-02-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('intro', models.CharField(default='Enter Intro Here...', max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('category', models.CharField(default='Enter category Here...', max_length=100)),
                ('weblink', models.CharField(default='Enter Url Here...', max_length=200)),
            ],
        ),
    ]
